// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-AtBFxnw7gQHwl0CAyWPHblm4Z7Q9itc',
    appId: '1:405936423555:android:7ab6d5e1a9aa238267d1b6',
    messagingSenderId: '405936423555',
    projectId: 'solar-panel-cleaning-bot',
    databaseURL: 'https://solar-panel-cleaning-bot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-panel-cleaning-bot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8f0W2dPs1tywgWnDeA0rl6onorCM8N48',
    appId: '1:405936423555:ios:405ac7001a22aa9367d1b6',
    messagingSenderId: '405936423555',
    projectId: 'solar-panel-cleaning-bot',
    databaseURL: 'https://solar-panel-cleaning-bot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-panel-cleaning-bot.appspot.com',
    iosClientId: '405936423555-8doe9avmpu1dr7ojjfbeiffils8roc1g.apps.googleusercontent.com',
    iosBundleId: 'com.pec.solarPanelCleaningBot',
  );
}
